<!--page specific css styles-->
<link rel="stylesheet" href="<?php echo __TEMPLATE_URL; ?>assets/data-tables/DT_bootstrap.css" />

<table id="table2" class="table table-striped table-hover fill-head dataTable" aria-describedby="table1_info">
    <thead>
    <tr>
        <th width="2%" class="nosort">#</th>
        <th class="col_link">Name</th>
        <th width="150px" class="col_datetime">Last Update</th>
        <th style="width: 100px;text-align: center" class="col_active">Active</th>
        <th style="width: 70px" class="col_action">Action</th>
    </tr>
    </thead>
    <tbody></tbody>
</table>

<script type="text/javascript">
    $(document).ready(function()
    {
        var table = $('#table2').on('processing.dt', function ( e, settings, processing ) {
            $('#processingIndicator').css( 'display', processing ? 'block' : 'none' );
            if(processing)
                console.log('loading ne');
            else
                console.log('loading xong roi');
            // -- su ly processing --
        }).DataTable({
            'aoColumnDefs': [
            {
                'bSortable': false,
                'bSearchable': false,
                'aTargets': ['nosort']
            },{
                'bSortable': true,
                'bSearchable': true,
                'aTargets': ['col_link'], // Column to target
                "mRender": function ( data, type, row ) {
                    // 'row' is the row's data object, and 'data' is this column's data
                    // e.g. 'row[0]' is the comic id, and 'data' is the comic title
                    html = '<a title="" href="<?= $update_link; ?>'+'/'+row[0]+'">'+data+'</a>';
                    return html;
                }
            },{
                'bSortable': true,
                'bSearchable': false,
                'aTargets': ['col_datetime'] // Column to target
            },{
                'bSortable': false,
                'bSearchable': false,
                'sClass': 'text-center',
                'aTargets': ['col_active'], // Column to target
                'mRender': function ( data, type, row ) {
                    html = "<a href='#' title='UnActive' class='btn btn-circle btn-gray'><i class='icon-remove-circle'></i></a>";
                    if (data == 1)
                        html = "<a href='#' title='Active' class='btn btn-circle btn-lime'><i class='icon-ok-sign'></i></a>";
                    return html;
                }
            },{
                'bSortable': false,
                'bSearchable': false,
                'aTargets': ['col_action'], // Column to target
                'mRender': function ( data, type, row ) {
                    html = '<a class="btn btn-small btn-gray" title="" href="<?php echo $update_link; ?>/'+row[0]+'"><i class="icon-edit"></i></a>';
                    html += '<a class="btn btn-small btn-danger" title="" href="javascript:confimDelete(\'<?php echo $delete_link; ?>/'+row[0]+'\');"><i class="icon-trash"></i></a>';
                    return html;
                }
            }],
            "bProcessing": true,
            "bServerSide": true,
            "sAjaxSource": "<?= $load_data_link; ?>",
//            "iDisplayLength": 25, // Default show rows
            "aLengthMenu": [[10, 25, 50, 100, -1], [10, 25, 50, 100, 'All']],
            "processing" : true,
//            "sPaginationType": "bootstrap"
            "sPaginationType": "full_numbers"
        });

    });
</script>

<!--page specific plugin scripts-->
<script type="text/javascript" src="<?php echo __TEMPLATE_URL; ?>assets/data-tables/jquery.dataTables.js"></script>
<script type="text/javascript" src="<?php echo __TEMPLATE_URL; ?>assets/data-tables/DT_bootstrap.js"></script>
